FROM eclipse-temurin:21-jdk AS builder

ARG MYSQL_URL
ARG MYSQL_USERNAME
ARG MYSQL_PORT
ARG MYSQL_DATABASE
ARG MYSQL_ROOT_PASSWORD
ARG OPENAI_KEY
ARG PINECONE_KEY
ARG PINECONE_PROJECT_ID
ARG PINECONE_REGION
ARG TTS_SERVER_URL
ARG JWT_SECRET
ARG OAUTH_GOOGLE_CLIENT_SECRET
ARG OAUTH_GOOGLE_CLIENT_ID


ENV MYSQL_URL=$MYSQL_URL \
    MYSQL_USERNAME=$MYSQL_USERNAME \
    MYSQL_PORT=$MYSQL_PORT \
    MYSQL_DATABASE=$MYSQL_DATABASE \
    MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD \
    OPENAI_KEY=$OPENAI_KEY \
    PINECONE_KEY=$PINECONE_KEY \
    PINECONE_PROJECT_ID=$PINECONE_PROJECT_ID \
    PINECONE_REGION=$PINECONE_REGION \
    TTS_SERVER_URL=$TTS_SERVER_URL \
    JWT_SECRET=$JWT_SECRET \
    OAUTH_GOOGLE_CLIENT_SECRET=$OAUTH_GOOGLE_CLIENT_SECRET \
    OAUTH_GOOGLE_CLIENT_ID=$OAUTH_GOOGLE_CLIENT_ID

WORKDIR /app
COPY . /app

# 잠시 테스트 스킵: ./gradlew clean build -x test
RUN ./gradlew clean build -x test

FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=builder /app/build/libs/*.jar /app/streamx-0.0.5-RC2.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "streamx-0.0.5-RC2.jar", "--spring.profiles.active=product"]
