spring:
  application:
    name: streamx_BE

  config:
    import: optional:file:.env[.properties]
  profiles:
    active: develop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 베타 버전 배포시 validate로 변경
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    chat:
      memory:
        repository:
          jdbc:
            schema: classpath:/sql/schema-mysql.sql
            initialize-schema: always
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.6
      embedding:
        options:
          model: text-embedding-3-large

    vectorstore:
      pinecone:
        api-key: ${PINECONE_KEY}
        project-id: ${PINECONE_PROJECT_ID}
        environment: ${PINECONE_REGION}
        index-name: stream-x