spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}

  docker:
    compose:
      enabled: false

tts:
  api:
    url: localhost:9338
